### ISSUE TITLE
Como usuario nuevo, me gustaría poder registrarme de manera sencilla para poder ingresar posteriormente con mis datos registrados.

### ISSUE THREAD

**Issue by Vadhir8** [4GeeksAcademy/ProyectoFinal-Latam36-Financiero4G#2]

**Comment by EnriqueLopez4G** [comment]
- [x] Crear  una estructura  basica de directorios para el inicio del desarrollo de la aplicacion
- [x]  Completar el componente App para manejar el sistema de rutas inicial de aplicacion
- [x] Crear una componente react que sea una vista para que el usuario pueda darse de alta en la app pidiendo los datos de nombre de usuario, correo y contraseñ, y estos datos enviarlos a la ruta de back respectiva.
- [x] Crear un modelo en el Back llamado Usuarios  para que se añada la tabla con mismo nombre a la base de datos
- [x] Crear un endpoint en el back que permita recibir los datos de nombre_usuario, correo, contrasena validarlos y guardarlos en la tabla usuarios
- [x] Crear un componente react que sea una vista para que el usuario puede registrarse para ingresar a la app donde se le pedira su correo y su contraseña y si es primera vez que ingresa se le pedira su capital inicial y la moneda con que manejara sus datos monetarios.
- [x] Crear un endpoint en el back para que un usuario previamente registrado en la base de datos, puede recibir  su id, correo, capital inicial  y su moneda , los valide, genere token y  token y status al front.
