### ISSUE TITLE
Como usuario me gustaría poder ver los registros de mis ingresos y egresos de manera gráfica.

### ISSUE THREAD

**Issue by Vadhir8** [4GeeksAcademy/ProyectoFinal-Latam36-Financiero4G#9]

**Comment by EnriqueLopez4G** [comment]
**Dashboard`**
- [x]  Crear el diseño visual y la estructura de la interfaz de usuario para mostrar los gráficos de ingresos, egresos y planes de ahorro.
- [x] Identificar las ubicaciones y dimensiones de cada gráfico (pie chart para ingresos y egresos, line chart para evolución de egresos/ingresos, progress bar para el plan de ahorro).
- [x] Implementar el gráfico de pastel que muestre la distribución de ingresos y egresos en un mismo gráfico o en gráficos separados
- [x] Implementar el gráfico de líneas que muestre la evolución de ingresos y egresos a lo largo del tiempo.
- [x] Implementar la barra de progreso para mostrar el avance de los planes de ahorro hacia un objetivo predeterminado.

- [x] Determinar qué registros de ingresos (por ejemplo, pagos recibidos, salario, etc.) se mostrarán.
- [x] Determinar qué registros de egresos (por ejemplo, gastos fijos, compras, pagos) se mostrarán.
- [x] Definir cómo se calcularán los planes de ahorro (por ejemplo, un objetivo mensual o anual).
- [x] Asegurarse de que los datos estén correctamente estructurados en la base de datos y en la  API
